### ISSUE TITLE
Unable to create user, error in middleware

### ISSUE THREAD

**Issue by Tanmoy037** [Tanmoy037/youtube-backend#2]
error in the terminal -

MulterError: Unexpected field
    at wrappedFileFilter (/Users/tanmoy/development/youtubeBackendInjs/node_modules/multer/index.js:40:19)
    at Multipart.<anonymous> (/Users/tanmoy/development/youtubeBackendInjs/node_modules/multer/lib/make-middleware.js:107:7)
    at Multipart.emit (node:events:513:28)
    at HeaderParser.cb (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:358:14)
    at HeaderParser.push (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:162:20)
    at SBMH.ssCb [as _cb] (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:394:37)
    at feed (/Users/tanmoy/development/youtubeBackendInjs/node_modules/streamsearch/lib/sbmh.js:219:14)
    at SBMH.push (/Users/tanmoy/development/youtubeBackendInjs/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:392:12)
   
error in postman - 
    
 <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>MulterError: Unexpected field<br> &nbsp; &nbsp;at wrappedFileFilter (/Users/tanmoy/development/youtubeBackendInjs/node_modules/multer/index.js:40:19)<br> &nbsp; &nbsp;at Multipart.&lt;anonymous&gt; (/Users/tanmoy/development/youtubeBackendInjs/node_modules/multer/lib/make-middleware.js:107:7)<br> &nbsp; &nbsp;at Multipart.emit (node:events:513:28)<br> &nbsp; &nbsp;at HeaderParser.cb (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:358:14)<br> &nbsp; &nbsp;at HeaderParser.push (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:162:20)<br> &nbsp; &nbsp;at SBMH.ssCb [as _cb] (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:394:37)<br> &nbsp; &nbsp;at feed (/Users/tanmoy/development/youtubeBackendInjs/node_modules/streamsearch/lib/sbmh.js:219:14)<br> &nbsp; &nbsp;at SBMH.push (/Users/tanmoy/development/youtubeBackendInjs/node_modules/streamsearch/lib/sbmh.js:104:16)<br> &nbsp; &nbsp;at Multipart._write (/Users/tanmoy/development/youtubeBackendInjs/node_modules/busboy/lib/types/multipart.js:567:19)<br> &nbsp; &nbsp;at writeOrBuffer (node:internal/streams/writable:392:12)</pre>
</body>

</html>

**Comment by Tanmoy037** [comment]
Fixed!
